version: "3.6"

services:
  socket-proxy:
    image: ghcr.io/bmoers/sn/sn-docker-socket-proxy:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    networks:
      - web
    ports:
      - 8080:8080

networks:
  web:
    driver: bridge
