version: "3.6"

services:
  socket-proxy:
    build: .
    platform: linux/amd64
    env_file: .env
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.htpasswd:/usr/src/app/.htpasswd
      - ./logs:/usr/src/app/logs
    networks:
      - web
    ports:
      - 8080:8080

networks:
  web:
    driver: bridge
