name: Docker Image CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prep Tags
        id: prep
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          TAGS="ghcr.io/bmoers/sn/sn-docker-socket-proxy:latest"
          TAGS="$TAGS,ghcr.io/bmoers/sn/sn-docker-socket-proxy:sha-${GITHUB_SHA::8}"
          TAGS="$TAGS,ghcr.io/bmoers/sn/sn-docker-socket-proxy:${VERSION}"
          echo ::set-output name=tags::${TAGS}

      - name: Build Docker images & push to Github Packages
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          pull: false
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=Docker Socket Proxy for ServiceNow ATF Headless Browser Integration with Azure

      - name: Prune Docker images
        uses: vlaurin/action-ghcr-prune@main
        with:
          container: sn/sn-docker-socket-proxy
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          dry-run: false
          keep-last: 5
          untagged: true
